In [81]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Torch 
import torch
import torch.nn as nn
from transformers import BertTokenizer, BertModel

# Scikit-Learn
# Data Encoding and Scaling
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder, StandardScaler
from sklearn.decomposition import PCA

# Natural Language Processing(NLP)
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

C:\Users\Dushyant\Downloads\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
nltk.download('punkt')      # For tokenization
nltk.download('stopwords')  # For stopword removal

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Dushyant\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dushyant\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [4]:
df = pd.read_csv('IntervieweeDataset.csv')

In [5]:
df.head(1)

,Name,Age,Gender,Type of Graduation/Post Graduation,Marital status,Mode of interview given by candidate?,Pre Interview Check,Fluency in English based on introduction,Confidence based on Introduction (English),Confidence based on the topic given,...,Structured Thinking Based on the PPT Question.1,Structured Thinking( Call pitch).1,Regional fluency based on the topic given .1,Regional fluency Based on the PPT Question.1,Regional fluency based on the sales scenario.1,Confidence Score,Structured Thinking Score,Regional Fluency Score,Total Score,Whether joined the company or not\n
0,parida,25,Female,Masters in data science,Unmarried,Mobile,Proceed with the Interview,Able to speak sentences in a clear/coherent wa...,Impactful - Good confidence throughout the Int...,Guarded Confidence - Confident in some areas a...,...,3,2,1,1.0,1.0,11,7,3,42,No

In [6]:
df.shape

(21256, 52)

In [7]:
df.dropna(inplace=True)

In [8]:
df.shape

(18681, 52)

In [9]:
df.drop(df.iloc[:,8:18], axis=1, inplace=True)

In [10]:
df.drop(['Does the candidate has mother tongue influence while speaking english.', 'How many slides candidate have submitted in PPT?'], axis=1, inplace=True)

In [11]:
df.shape

(18681, 40)

In [12]:
df.rename(columns={'Type of Graduation/Post Graduation':'Education', 'Mode of interview given by candidate?':'Mode of Interview', 'Has acquaintance in Company and has spoken to him/her before applying?':'Acquaintance and Referral'}, inplace=True)

In [13]:
df.rename(columns={'Whether joined the company or not\n': 'Whether joined the company or not', 'What was the type of Role?\t': 'What was the type of Role?'}, inplace=True)

In [14]:
df.rename(columns={"But, my child's exam are going on now, so we will keep the counselling session after the exams get over.(Time: Favourable pitch: Counsellor hype)":"But, my child's exam are going on now, so we will keep the counselling session after the exams get over"}, inplace=True)

In [15]:
df.columns

Index(['Name', 'Age', 'Gender', 'Education', 'Marital status',
       'Mode of Interview', 'Pre Interview Check',
       'Fluency in English based on introduction', 'Acquaintance and Referral',
       'Candidate Status', 'Last Fixed CTC (lakhs) ', 'Currently Employed',
       'Experienced candidate - (Experience in months)',
       'Experienced Candidate (Nature of work)', 'What was the type of Role?',
       'Call-pitch Elements used during the call Sales Scenario',
       'But, my child's exam are going on now, so we will keep the counselling session after the exams get over',
       'Let me discuss it with my child',
       'Sir being in education industry I know this is a marketing gimmick and at the end of the day you'll be selling the app.',
       'Role acceptance', 'Interview Verdict',
       'Candidate is willing to relocate',
       'Role Location to be given to the candidate', 'Comments',
       'RedFlags Comments in Interview',
       'Confidence based on Introduction (English).1',
       'Confidence based on the topic given  .1',
       'Confidence Based on the PPT Question.1',
       'Confidence based on the sales scenario.1',
       'Structured Thinking (In regional only).1',
       'Structured Thinking Based on the PPT Question.1',
       'Structured Thinking( Call pitch).1',
       'Regional fluency based on the topic given  .1',
       'Regional fluency Based on the PPT Question.1',
       'Regional fluency based on the  sales scenario.1', 'Confidence Score',
       'Structured Thinking Score', 'Regional Fluency Score', 'Total Score',
       'Whether joined the company or not'],
      dtype='object')

In [16]:
df['Age'].unique()

array(['25', '29', '27', '22', '23', '24', '26', '21', '30', '20', '31',
       '28', '32+', '32'], dtype=object)

In [17]:
df['Age'] = df['Age'].astype(str).str.replace('+', '', regex=False).astype(int)

In [18]:
df['Age'].unique()

array([25, 29, 27, 22, 23, 24, 26, 21, 30, 20, 31, 28, 32])

In [19]:
bins = [18, 22, 25, 28, 32, 35, float('inf')]
labels = ['18-22', '23-25', '26-28', '29-32', '33-35', '35+']

In [20]:
df['Age'] = pd.cut(df['Age'], bins=bins, labels=labels, right=True)

In [21]:
df.isnull().sum()

Name                                                                                                                       0
Age                                                                                                                        0
Gender                                                                                                                     0
Education                                                                                                                  0
Marital status                                                                                                             0
Mode of Interview                                                                                                          0
Pre Interview Check                                                                                                        0
Fluency in English based on introduction                                                                                   0
Acquaintance and Referral                                                                                                  0
Candidate Status                                                                                                           0
Last Fixed CTC (lakhs)                                                                                                     0
Currently Employed                                                                                                         0
Experienced candidate - (Experience in months)                                                                             0
Experienced Candidate (Nature of work)                                                                                     0
What was the type of Role?                                                                                                 0
Call-pitch Elements used during the call Sales Scenario                                                                    0
But, my child's exam are going on now, so we will keep the counselling session after the exams get over                    0
Let me discuss it with my child                                                                                            0
Sir being in education industry I know this is a marketing gimmick and at the end of the day you'll be selling the app.    0
Role acceptance                                                                                                            0
Interview Verdict                                                                                                          0
Candidate is willing to relocate                                                                                           0
Role Location to be given to the candidate                                                                                 0
Comments                                                                                                                   0
RedFlags Comments in Interview                                                                                             0
Confidence based on Introduction (English).1                                                                               0
Confidence based on the topic given  .1                                                                                    0
Confidence Based on the PPT Question.1                                                                                     0
Confidence based on the sales scenario.1                                                                                   0
Structured Thinking (In regional only).1                                                                                   0
Structured Thinking Based on the PPT Question.1                                                                            0
Structured Thinking( Call pitch).1                                                                                         0
Regional fluency based on the topic given  .1                                                                              0
Regional fluency Based on the PPT Question.1                                                                               0
Regional fluency based on the  sales scenario.1                                                                            0
Confidence Score                                                                                                           0
Structured Thinking Score                                                                                                  0
Regional Fluency Score                                                                                                     0
Total Score                                                                                                                0
Whether joined the company or not                                                                                          0
dtype: int64

In [22]:
df['Age'].unique()

['23-25', '29-32', '26-28', '18-22']
Categories (6, object): ['18-22' < '23-25' < '26-28' < '29-32' < '33-35' < '35+']

In [23]:
df.columns

Index(['Name', 'Age', 'Gender', 'Education', 'Marital status',
       'Mode of Interview', 'Pre Interview Check',
       'Fluency in English based on introduction', 'Acquaintance and Referral',
       'Candidate Status', 'Last Fixed CTC (lakhs) ', 'Currently Employed',
       'Experienced candidate - (Experience in months)',
       'Experienced Candidate (Nature of work)', 'What was the type of Role?',
       'Call-pitch Elements used during the call Sales Scenario',
       'But, my child's exam are going on now, so we will keep the counselling session after the exams get over',
       'Let me discuss it with my child',
       'Sir being in education industry I know this is a marketing gimmick and at the end of the day you'll be selling the app.',
       'Role acceptance', 'Interview Verdict',
       'Candidate is willing to relocate',
       'Role Location to be given to the candidate', 'Comments',
       'RedFlags Comments in Interview',
       'Confidence based on Introduction (English).1',
       'Confidence based on the topic given  .1',
       'Confidence Based on the PPT Question.1',
       'Confidence based on the sales scenario.1',
       'Structured Thinking (In regional only).1',
       'Structured Thinking Based on the PPT Question.1',
       'Structured Thinking( Call pitch).1',
       'Regional fluency based on the topic given  .1',
       'Regional fluency Based on the PPT Question.1',
       'Regional fluency based on the  sales scenario.1', 'Confidence Score',
       'Structured Thinking Score', 'Regional Fluency Score', 'Total Score',
       'Whether joined the company or not'],
      dtype='object')

In [24]:
new_df = df[['Confidence based on Introduction (English).1',
       'Confidence based on the topic given  .1',
       'Confidence Based on the PPT Question.1',
       'Confidence based on the sales scenario.1',
       'Structured Thinking (In regional only).1',
       'Structured Thinking Based on the PPT Question.1',
       'Structured Thinking( Call pitch).1',
       'Regional fluency based on the topic given  .1',
       'Regional fluency Based on the PPT Question.1',
       'Regional fluency based on the  sales scenario.1', 'Confidence Score',
       'Structured Thinking Score', 'Regional Fluency Score', 'Total Score',]]

In [25]:
new_df.head(1)

,Confidence based on Introduction (English).1,Confidence based on the topic given .1,Confidence Based on the PPT Question.1,Confidence based on the sales scenario.1,Structured Thinking (In regional only).1,Structured Thinking Based on the PPT Question.1,Structured Thinking( Call pitch).1,Regional fluency based on the topic given .1,Regional fluency Based on the PPT Question.1,Regional fluency based on the sales scenario.1,Confidence Score,Structured Thinking Score,Regional Fluency Score,Total Score
0,3,2,3,3,2,3,2,1,1.0,1.0,11,7,3,42

new_df.info()

In [26]:
df.shape

(18681, 40)

In [27]:
df['id'] = df.index

In [28]:
df.head()

,Name,Age,Gender,Education,Marital status,Mode of Interview,Pre Interview Check,Fluency in English based on introduction,Acquaintance and Referral,Candidate Status,...,Structured Thinking( Call pitch).1,Regional fluency based on the topic given .1,Regional fluency Based on the PPT Question.1,Regional fluency based on the sales scenario.1,Confidence Score,Structured Thinking Score,Regional Fluency Score,Total Score,Whether joined the company or not,id
0,parida,23-25,Female,Masters in data science,Unmarried,Mobile,Proceed with the Interview,Able to speak sentences in a clear/coherent wa...,No,Experienced in non client facing(equal to or m...,...,2,1,1.0,1.0,11,7,3,42,No,0
1,shreej,29-32,Female,BSc or MSc,Unmarried,Mobile,Proceed with the Interview,Able to speak sentences in a clear/coherent wa...,No,Lateral(2021 and before with (less than 6 mont...,...,3,3,3.0,3.0,12,9,9,60,No,1
2,ms6744,26-28,Female,B.E / B-Tech,Unmarried,Mobile,Proceed with the Interview,Able to speak sentences in a clear/coherent wa...,Yes,Fresher(only 2022 grad),...,3,3,1.0,3.0,10,9,7,52,Yes,2
3,aswalu,18-22,Male,B.E / B-Tech,Unmarried,Laptop,Proceed with the Interview,Able to speak sentences in a clear/coherent wa...,No,Fresher(only 2022 grad),...,3,3,3.0,3.0,12,9,9,60,Yes,3
4,aniket,18-22,Male,BA/MA,Unmarried,Mobile,Proceed with the Interview,Taking gaps while speaking due to lack of cont...,No,Fresher(only 2022 grad),...,1,3,1.0,3.0,10,5,7,44,Not Joined,4

# New Dataframe for only Numerical Operations (excluding Name column from it)

In [29]:
numerical_df = df.copy()
numerical_df.drop(['id',
                   'Name',
                   'Comments',
                   'RedFlags Comments in Interview',
                   'Call-pitch Elements used during the call Sales Scenario',
                   "But, my child's exam are going on now, so we will keep the counselling session after the exams get over",
                  'Let me discuss it with my child',
                   "Sir being in education industry I know this is a marketing gimmick and at the end of the day you'll be selling the app.",'Role Location to be given to the candidate'],
                  axis=1,inplace=True)

# Data Scaling
The StandardScaler from sklearn.preprocessing transforms data to have:

Mean = 0 ,
Standard Deviation = 1

In [30]:
scaler = StandardScaler()
scaler

StandardScaler()

In [31]:
temp_list = ['Confidence based on Introduction (English).1',
       'Confidence based on the topic given  .1',
       'Confidence Based on the PPT Question.1',
       'Confidence based on the sales scenario.1',
       'Structured Thinking (In regional only).1',
       'Structured Thinking Based on the PPT Question.1',
       'Structured Thinking( Call pitch).1',
       'Regional fluency based on the topic given  .1',
       'Regional fluency Based on the PPT Question.1',
       'Regional fluency based on the  sales scenario.1', 'Confidence Score',
       'Structured Thinking Score', 'Regional Fluency Score', 'Total Score']

In [32]:
numerical_df[temp_list] = scaler.fit_transform(numerical_df[temp_list])
print("Means after scaling:\n", numerical_df[temp_list].mean().round(5))
print("Standard deviations after scaling:\n", numerical_df[temp_list].std().round(5))

Means after scaling:
 Confidence based on Introduction (English).1      -0.0
Confidence based on the topic given  .1           -0.0
Confidence Based on the PPT Question.1            -0.0
Confidence based on the sales scenario.1          -0.0
Structured Thinking (In regional only).1           0.0
Structured Thinking Based on the PPT Question.1   -0.0
Structured Thinking( Call pitch).1                -0.0
Regional fluency based on the topic given  .1      0.0
Regional fluency Based on the PPT Question.1      -0.0
Regional fluency based on the  sales scenario.1   -0.0
Confidence Score                                   0.0
Structured Thinking Score                         -0.0
Regional Fluency Score                             0.0
Total Score                                        0.0
dtype: float64
Standard deviations after scaling:
 Confidence based on Introduction (English).1       1.00003
Confidence based on the topic given  .1            1.00003
Confidence Based on the PPT Question.1             1.00003
Confidence based on the sales scenario.1           1.00003
Structured Thinking (In regional only).1           1.00003
Structured Thinking Based on the PPT Question.1    1.00003
Structured Thinking( Call pitch).1                 1.00003
Regional fluency based on the topic given  .1      1.00003
Regional fluency Based on the PPT Question.1       1.00003
Regional fluency based on the  sales scenario.1    1.00003
Confidence Score                                   1.00003
Structured Thinking Score                          1.00003
Regional Fluency Score                             1.00003
Total Score                                        1.00003
dtype: float64

In [33]:
numerical_df.head()

,Age,Gender,Education,Marital status,Mode of Interview,Pre Interview Check,Fluency in English based on introduction,Acquaintance and Referral,Candidate Status,Last Fixed CTC (lakhs),...,Structured Thinking Based on the PPT Question.1,Structured Thinking( Call pitch).1,Regional fluency based on the topic given .1,Regional fluency Based on the PPT Question.1,Regional fluency based on the sales scenario.1,Confidence Score,Structured Thinking Score,Regional Fluency Score,Total Score,Whether joined the company or not
0,23-25,Female,Masters in data science,Unmarried,Mobile,Proceed with the Interview,Able to speak sentences in a clear/coherent wa...,No,Experienced in non client facing(equal to or m...,5-5.99,...,1.020654,-0.424411,-1.092966,-1.063625,-1.043289,0.951490,-0.022276,-1.320677,-0.198863,No
1,29-32,Female,BSc or MSc,Unmarried,Mobile,Proceed with the Interview,Able to speak sentences in a clear/coherent wa...,No,Lateral(2021 and before with (less than 6 mont...,Fresher,...,1.020654,1.006713,0.979581,1.024503,1.060405,1.415087,1.256178,1.264403,1.509342,No
2,26-28,Female,B.E / B-Tech,Unmarried,Mobile,Proceed with the Interview,Able to speak sentences in a clear/coherent wa...,Yes,Fresher(only 2022 grad),Fresher,...,1.020654,1.006713,0.979581,-1.063625,1.060405,0.487893,1.256178,0.402709,0.750139,Yes
3,18-22,Male,B.E / B-Tech,Unmarried,Laptop,Proceed with the Interview,Able to speak sentences in a clear/coherent wa...,No,Fresher(only 2022 grad),Fresher,...,1.020654,1.006713,0.979581,1.024503,1.060405,1.415087,1.256178,1.264403,1.509342,Yes
4,18-22,Male,BA/MA,Unmarried,Mobile,Proceed with the Interview,Taking gaps while speaking due to lack of cont...,No,Fresher(only 2022 grad),Fresher,...,-0.556030,-1.855535,0.979581,-1.063625,1.060405,0.487893,-1.300729,0.402709,-0.009063,Not Joined

In [34]:
numerical_df.shape

(18681, 32)

# Data Encoding

In [35]:
numerical_df['Role acceptance'].value_counts()

Role acceptance
Emphatic Yes                                        12456
Yes : Think and says yes.(Shows some hesitation)     5475
No                                                    750
Name: count, dtype: int64

In [36]:
transformer = ColumnTransformer(transformers = [
    ('t1', OneHotEncoder(sparse_output=False, drop='first'), ['Gender', 'Experienced Candidate (Nature of work)', 'What was the type of Role?', 'Whether joined the company or not', 'Currently Employed', 'Marital status', 'Mode of Interview', 'Pre Interview Check', 'Fluency in English based on introduction', 'Acquaintance and Referral', 'Candidate Status', 'Education']),
    ('t2', OrdinalEncoder(categories=[['Fresher','0-1.99','2-2.99','3-3.99','4-4.99','5-5.99','6-6.99','7+']]), ['Last Fixed CTC (lakhs) ']),
    ('t3', OrdinalEncoder(categories=[['No - Want Specific Centre Location Only','Yes - Anywhere Within a City','Yes - Anywhere Within a State','Yes - Anywhere in PAN India']]), ['Candidate is willing to relocate']),
    ('t4', OrdinalEncoder(categories=[['Reject','Borderline Reject','Borderline Select','Select','Premium Select']]), ['Interview Verdict']),
    ('t5', OrdinalEncoder(categories=[['No','Yes : Think and says yes.(Shows some hesitation)','Emphatic Yes']]), ['Role acceptance']),
    ('t6', OrdinalEncoder(categories=[['Fresher(<6 months)','6-11.99 Months','12-17.99 Months','18-23.99 Months','24-29.99 Months','30-35.99 Months','36-47.99 Months','48+ Months']]), ['Experienced candidate - (Experience in months)']),
    ('t7', OrdinalEncoder(categories=[['18-22', '23-25', '26-28', '29-32', '33-35', '35+']]), ['Age'])
], remainder='passthrough')

In [37]:
numerical_df = transformer.fit_transform(numerical_df)

In [38]:
type(numerical_df)

numpy.ndarray

In [39]:
features_names = transformer.get_feature_names_out()
numerical_df = pd.DataFrame(numerical_df, columns=features_names)

In [40]:
numerical_df.shape

(18681, 1900)

In [41]:
numerical_df.head(2)

,t1__Gender_Male,t1__Experienced Candidate (Nature of work)_ DISPATCHER IN US COMPANY,t1__Experienced Candidate (Nature of work)_ Laboratory Attendant,t1__Experienced Candidate (Nature of work)_ Network Engineer,t1__Experienced Candidate (Nature of work)_ no,t1__Experienced Candidate (Nature of work)_ proctor,t1__Experienced Candidate (Nature of work)_-,t1__Experienced Candidate (Nature of work)_.,t1__Experienced Candidate (Nature of work)_/,t1__Experienced Candidate (Nature of work)_10 lakhs lone,...,remainder__Structured Thinking (In regional only).1,remainder__Structured Thinking Based on the PPT Question.1,remainder__Structured Thinking( Call pitch).1,remainder__Regional fluency based on the topic given .1,remainder__Regional fluency Based on the PPT Question.1,remainder__Regional fluency based on the sales scenario.1,remainder__Confidence Score,remainder__Structured Thinking Score,remainder__Regional Fluency Score,remainder__Total Score
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.618598,1.020654,-0.424411,-1.092966,-1.063625,-1.043289,0.951490,-0.022276,-1.320677,-0.198863
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.985514,1.020654,1.006713,0.979581,1.024503,1.060405,1.415087,1.256178,1.264403,1.509342

# Principal Component Analysis(PCA) for Dimensionality Reduction
**Required to reduce the number of features**

In [42]:
pca = PCA(n_components=0.95)
numerical_df = pca.fit_transform(numerical_df)

In [43]:
type(numerical_df)

numpy.ndarray

In [44]:
 features_names = pca.get_feature_names_out()
numerical_df = pd.DataFrame(numerical_df, columns=features_names)

In [45]:
type(numerical_df)

pandas.core.frame.DataFrame

In [46]:
numerical_df.shape

(18681, 23)

In [47]:
numerical_df.head()

,pca0,pca1,pca2,pca3,pca4,pca5,pca6,pca7,pca8,pca9,...,pca13,pca14,pca15,pca16,pca17,pca18,pca19,pca20,pca21,pca22
0,-0.052781,1.823040,-1.000861,-1.640338,2.153899,-0.904880,-3.322327,2.383088,1.147654,1.216667,...,-1.002317,-0.186995,1.102233,0.585393,0.070028,-0.435301,0.148319,-0.219776,-0.664650,-0.621672
1,2.923109,-2.272580,1.616185,0.522408,1.446041,1.329056,-1.950287,-1.941437,2.152077,0.779589,...,-0.057405,-0.829778,0.279894,-0.026051,0.470935,0.000236,-0.025792,0.042607,-0.017964,-0.339394
2,2.164853,-2.073269,-1.094714,-0.267596,-0.985760,0.299652,1.724536,-0.453220,1.248881,0.539528,...,-1.112322,0.481271,-0.121442,0.542240,0.176530,-0.313344,-0.809657,0.663573,0.696053,-0.599852
3,3.906563,-3.405313,-0.106782,1.147585,0.310900,-0.251753,0.245191,0.203074,-0.415105,-0.740198,...,-0.019635,0.724503,-0.090785,-0.022621,0.262717,-0.189576,-0.089993,-0.359328,0.102563,0.083939
4,-0.944235,-1.526629,1.590621,-1.558568,0.460823,-1.567873,1.634695,-0.184716,-0.024793,-0.146011,...,-1.064223,-0.125709,0.136476,0.183655,-0.484256,0.297118,-0.582925,-0.026695,-0.152585,0.173361

In [48]:
numerical_df.isnull().sum()

pca0     0
pca1     0
pca2     0
pca3     0
pca4     0
pca5     0
pca6     0
pca7     0
pca8     0
pca9     0
pca10    0
pca11    0
pca12    0
pca13    0
pca14    0
pca15    0
pca16    0
pca17    0
pca18    0
pca19    0
pca20    0
pca21    0
pca22    0
dtype: int64

In [49]:
df = df[['id',
                   'Name',
                   'Comments',
                   'RedFlags Comments in Interview',
                   'Call-pitch Elements used during the call Sales Scenario',
                   "But, my child's exam are going on now, so we will keep the counselling session after the exams get over",
                  'Let me discuss it with my child',
                   "Sir being in education industry I know this is a marketing gimmick and at the end of the day you'll be selling the app.",'Role Location to be given to the candidate']]

In [50]:
df.head()

,id,Name,Comments,RedFlags Comments in Interview,Call-pitch Elements used during the call Sales Scenario,"But, my child's exam are going on now, so we will keep the counselling session after the exams get over",Let me discuss it with my child,Sir being in education industry I know this is a marketing gimmick and at the end of the day you'll be selling the app.,Role Location to be given to the candidate
0,0,parida,"Lipsa is 25 female from Orissa, Family BG - Fa...",At least Graduated ( not 12th Pass or diploma ...,Purpose of Call (Book a Counselling Session),Urgency using Time,None of the above,None of the above,Bangalore
1,1,shreej,29 yo / female / unmarried / MSc Finance UK 20...,Not Rehire (CDT have not joined byjus in sales...,"Introduction (Self Intro,Company Name), Purpos...",Asking Questions,None of the above,Non chargeable session,Delhi
2,2,ms6744,nm,Not working currently and ready to join the R3...,"Introduction (Self Intro,Company Name)",Urgency using Time,Decision Making: Major decision of child futur...,Non chargeable session,Chennai
3,3,aswalu,Final Interview Done 22YRS //UTTARAKHAND // F...,Not Rehire (CDT have not joined byjus in sales...,"Introduction (Self Intro,Company Name), Purpos...","Urgency using Time, Urgency using situation",None of the above,Value creation(Nothing comes for free),Delhi
4,4,aniket,"Aniket is 22 male from Bhopal, BA Grad 21, Fam...","Age is below 32.11, At least Graduated ( not 1...",None of the Above,Urgency by creating counsellor Hype,Anticipation of objection from child's end:,Value creation(Nothing comes for free),Bangalore

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18681 entries, 0 to 21255
Data columns (total 9 columns):
 #   Column                                                                                                                   Non-Null Count  Dtype
---  ------                                                                                                                   --------------  -----
 0   id                                                                                                                       18681 non-null  int64
 1   Name                                                                                                                     18681 non-null  object
 2   Comments                                                                                                                 18681 non-null  object
 3   RedFlags Comments in Interview                                                                                           18681 non-null  object
 4   Call-pitch Elements used during the call Sales Scenario                                                                  18681 non-null  object
 5   But, my child's exam are going on now, so we will keep the counselling session after the exams get over                  18681 non-null  object
 6   Let me discuss it with my child                                                                                          18681 non-null  object
 7   Sir being in education industry I know this is a marketing gimmick and at the end of the day you'll be selling the app.  18681 non-null  object
 8   Role Location to be given to the candidate                                                                               18681 non-null  object
dtypes: int64(1), object(8)
memory usage: 1.4+ MB

In [52]:
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].apply(lambda x:x.split())

In [53]:
df.head()

,id,Name,Comments,RedFlags Comments in Interview,Call-pitch Elements used during the call Sales Scenario,"But, my child's exam are going on now, so we will keep the counselling session after the exams get over",Let me discuss it with my child,Sir being in education industry I know this is a marketing gimmick and at the end of the day you'll be selling the app.,Role Location to be given to the candidate
0,0,[parida],"[Lipsa, is, 25, female, from, Orissa,, Family,...","[At, least, Graduated, (, not, 12th, Pass, or,...","[Purpose, of, Call, (Book, a, Counselling, Ses...","[Urgency, using, Time]","[None, of, the, above]","[None, of, the, above]",[Bangalore]
1,1,[shreej],"[29, yo, /, female, /, unmarried, /, MSc, Fina...","[Not, Rehire, (CDT, have, not, joined, byjus, ...","[Introduction, (Self, Intro,Company, Name),, P...","[Asking, Questions]","[None, of, the, above]","[Non, chargeable, session]",[Delhi]
2,2,[ms6744],[nm],"[Not, working, currently, and, ready, to, join...","[Introduction, (Self, Intro,Company, Name)]","[Urgency, using, Time]","[Decision, Making:, Major, decision, of, child...","[Non, chargeable, session]",[Chennai]
3,3,[aswalu],"[Final, Interview, Done, 22YRS, //UTTARAKHAND,...","[Not, Rehire, (CDT, have, not, joined, byjus, ...","[Introduction, (Self, Intro,Company, Name),, P...","[Urgency, using, Time,, Urgency, using, situat...","[None, of, the, above]","[Value, creation(Nothing, comes, for, free)]",[Delhi]
4,4,[aniket],"[Aniket, is, 22, male, from, Bhopal,, BA, Grad...","[Age, is, below, 32.11,, At, least, Graduated,...","[None, of, the, Above]","[Urgency, by, creating, counsellor, Hype]","[Anticipation, of, objection, from, child's, e...","[Value, creation(Nothing, comes, for, free)]",[Bangalore]

In [54]:
df.columns

Index(['id', 'Name', 'Comments', 'RedFlags Comments in Interview',
       'Call-pitch Elements used during the call Sales Scenario',
       'But, my child's exam are going on now, so we will keep the counselling session after the exams get over',
       'Let me discuss it with my child',
       'Sir being in education industry I know this is a marketing gimmick and at the end of the day you'll be selling the app.',
       'Role Location to be given to the candidate'],
      dtype='object')

In [55]:
df['tags'] = df['Name'] + df['Comments'] + df['RedFlags Comments in Interview'] + df['Call-pitch Elements used during the call Sales Scenario'] + df["But, my child's exam are going on now, so we will keep the counselling session after the exams get over"] + df['Let me discuss it with my child'] + df["Sir being in education industry I know this is a marketing gimmick and at the end of the day you'll be selling the app."] + df['Role Location to be given to the candidate']

In [56]:
df.head()

,id,Name,Comments,RedFlags Comments in Interview,Call-pitch Elements used during the call Sales Scenario,"But, my child's exam are going on now, so we will keep the counselling session after the exams get over",Let me discuss it with my child,Sir being in education industry I know this is a marketing gimmick and at the end of the day you'll be selling the app.,Role Location to be given to the candidate,tags
0,0,[parida],"[Lipsa, is, 25, female, from, Orissa,, Family,...","[At, least, Graduated, (, not, 12th, Pass, or,...","[Purpose, of, Call, (Book, a, Counselling, Ses...","[Urgency, using, Time]","[None, of, the, above]","[None, of, the, above]",[Bangalore],"[parida, Lipsa, is, 25, female, from, Orissa,,..."
1,1,[shreej],"[29, yo, /, female, /, unmarried, /, MSc, Fina...","[Not, Rehire, (CDT, have, not, joined, byjus, ...","[Introduction, (Self, Intro,Company, Name),, P...","[Asking, Questions]","[None, of, the, above]","[Non, chargeable, session]",[Delhi],"[shreej, 29, yo, /, female, /, unmarried, /, M..."
2,2,[ms6744],[nm],"[Not, working, currently, and, ready, to, join...","[Introduction, (Self, Intro,Company, Name)]","[Urgency, using, Time]","[Decision, Making:, Major, decision, of, child...","[Non, chargeable, session]",[Chennai],"[ms6744, nm, Not, working, currently, and, rea..."
3,3,[aswalu],"[Final, Interview, Done, 22YRS, //UTTARAKHAND,...","[Not, Rehire, (CDT, have, not, joined, byjus, ...","[Introduction, (Self, Intro,Company, Name),, P...","[Urgency, using, Time,, Urgency, using, situat...","[None, of, the, above]","[Value, creation(Nothing, comes, for, free)]",[Delhi],"[aswalu, Final, Interview, Done, 22YRS, //UTTA..."
4,4,[aniket],"[Aniket, is, 22, male, from, Bhopal,, BA, Grad...","[Age, is, below, 32.11,, At, least, Graduated,...","[None, of, the, Above]","[Urgency, by, creating, counsellor, Hype]","[Anticipation, of, objection, from, child's, e...","[Value, creation(Nothing, comes, for, free)]",[Bangalore],"[aniket, Aniket, is, 22, male, from, Bhopal,, ..."

In [57]:
df.loc[1,'tags']

['shreej',
 '29',
 'yo',
 '/',
 'female',
 '/',
 'unmarried',
 '/',
 'MSc',
 'Finance',
 'UK',
 '2022',
 '/',
 'recently',
 'relocated',
 'to',
 'India',
 'just',
 '20',
 'days',
 'ago',
 '/',
 'Odissa',
 '/',
 'father',
 '-',
 'doctor',
 '/',
 'bro',
 '-',
 'software',
 'engineer',
 '/',
 'pursuing',
 'internship',
 'in',
 'investment',
 'banking',
 '-',
 'ends',
 'in',
 'next',
 'week',
 '/',
 'worked',
 'as',
 'a',
 'teacher',
 '/',
 'good',
 'story',
 'teller',
 '-',
 'fluent',
 'in',
 'hindi',
 'and',
 'english',
 '-',
 'good',
 'energy',
 '/',
 'also',
 'prepared',
 'for',
 'UPSC',
 'and',
 'GMAT',
 '-',
 'purchased',
 'a',
 'course',
 'from',
 "byju's",
 'earlier',
 '/',
 'cracked',
 'GMAT',
 'and',
 'got',
 'business',
 'school',
 'as',
 'well/asking',
 'ques',
 'in',
 'sales',
 'scenario',
 '-',
 '2/5',
 'Not',
 'Rehire',
 '(CDT',
 'have',
 'not',
 'joined',
 'byjus',
 'in',
 'sales',
 'before),',
 'Not',
 'Interviewed',
 'in',
 'Byjus',
 'in',
 'sales',
 'role',
 'in',
 'last',
 '90days,',
 'Laptop',
 'and',
 'WiFi',
 'are',
 'Available,',
 'Age',
 'is',
 'below',
 '32.11,',
 'At',
 'least',
 'Graduated',
 '(',
 'not',
 '12th',
 'Pass',
 'or',
 'diploma',
 'or',
 'Final',
 'Year',
 'student),',
 'Willing',
 'to',
 'relocate',
 'at',
 'given',
 'location',
 'for',
 'SSP,',
 'Comfortable',
 'with',
 'the',
 'stipend',
 '&',
 'allowances',
 'during',
 'training,',
 'Not',
 'working',
 'currently',
 'and',
 'ready',
 'to',
 'join',
 'the',
 'R3',
 'Process',
 'Introduction',
 '(Self',
 'Intro,Company',
 'Name),',
 'Purpose',
 'of',
 'Call',
 '(Book',
 'a',
 'Counselling',
 'Session),',
 'Need',
 'Generation',
 '-',
 'By',
 'Asking',
 'ques',
 'like',
 'student',
 'class,',
 'performance',
 'etc..',
 'Asking',
 'Questions',
 'None',
 'of',
 'the',
 'above',
 'Non',
 'chargeable',
 'session',
 'Delhi']

In [58]:
df = df[['id','Name','tags']]

In [59]:
df.head(1)

   id      Name                                               tags
0   0  [parida]  [parida, Lipsa, is, 25, female, from, Orissa,,...

## Stemming
**Note: Use Lemmatization for more accuracy**

To normalize words and reduce them to their root forms, we will apply **stemming**. This helps in handling variations of words and improves text processing efficiency for machine learning models.  
(e.g., "running" â†’ "run")

In [60]:
ps = PorterStemmer()
ps

In [61]:
stop_words = set(stopwords.words('english'))

In [62]:
def stem(text):
    y = []

    for i in text:
        y.append(ps.stem(i))

    return " ".join(y)

In [63]:
''' Applying Stemming '''

df['tags'] = df['tags'].apply(stem)

In [64]:
df.head()

   id      Name                                               tags
0   0  [parida]  parida lipsa is 25 femal from orissa, famili b...
1   1  [shreej]  shreej 29 yo / femal / unmarri / msc financ uk...
2   2  [ms6744]  ms6744 nm not work current and readi to join t...
3   3  [aswalu]  aswalu final interview done 22yr //uttarakhand...
4   4  [aniket]  aniket aniket is 22 male from bhopal, ba grad ...

In [65]:
df.loc[1,'tags']

"shreej 29 yo / femal / unmarri / msc financ uk 2022 / recent reloc to india just 20 day ago / odissa / father - doctor / bro - softwar engin / pursu internship in invest bank - end in next week / work as a teacher / good stori teller - fluent in hindi and english - good energi / also prepar for upsc and gmat - purchas a cours from byju' earlier / crack gmat and got busi school as well/ask que in sale scenario - 2/5 not rehir (cdt have not join byju in sale before), not interview in byju in sale role in last 90days, laptop and wifi are available, age is below 32.11, at least graduat ( not 12th pass or diploma or final year student), will to reloc at given locat for ssp, comfort with the stipend & allow dure training, not work current and readi to join the r3 process introduct (self intro,compani name), purpos of call (book a counsel session), need gener - by ask que like student class, perform etc.. ask question none of the abov non chargeabl session delhi"

In [66]:
df.isnull().sum()

id      0
Name    0
tags    0
dtype: int64

In [67]:
def stopwords_removal(text):
    words = word_tokenize(text.lower())
    filtered_words = [word for word in words if word not in stop_words]
    return " ".join(filtered_words)

In [68]:
''' Applying Stopwords Removal '''

df['tags'] = df['tags'].apply(stopwords_removal)

In [69]:
df.head(2)

   id      Name                                               tags
0   0  [parida]  parida lipsa 25 femal orissa , famili bg - fat...
1   1  [shreej]  shreej 29 yo / femal / unmarri / msc financ uk...

In [70]:
df.loc[1,'tags']

"shreej 29 yo / femal / unmarri / msc financ uk 2022 / recent reloc india 20 day ago / odissa / father - doctor / bro - softwar engin / pursu internship invest bank - end next week / work teacher / good stori teller - fluent hindi english - good energi / also prepar upsc gmat - purchas cours byju ' earlier / crack gmat got busi school well/ask que sale scenario - 2/5 rehir ( cdt join byju sale ) , interview byju sale role last 90days , laptop wifi available , age 32.11 , least graduat ( 12th pass diploma final year student ) , reloc given locat ssp , comfort stipend & allow dure training , work current readi join r3 process introduct ( self intro , compani name ) , purpos call ( book counsel session ) , need gener - ask que like student class , perform etc .. ask question none abov non chargeabl session delhi"

In [71]:
def remove_duplicates(text):
    words = text.split()
    seen = set()
    unique_words = []

    for word in words:
        if word not in seen:
            seen.add(word)
            unique_words.append(word)

    return " ".join(unique_words)

In [72]:
df['tags'] = df['tags'].apply(remove_duplicates)

In [73]:
df['tags'] = df['tags'].str.replace('/', '', regex=False)

In [74]:
df.loc[1,'tags']

"shreej 29 yo  femal unmarri msc financ uk 2022 recent reloc india 20 day ago odissa father - doctor bro softwar engin pursu internship invest bank end next week work teacher good stori teller fluent hindi english energi also prepar upsc gmat purchas cours byju ' earlier crack got busi school wellask que sale scenario 25 rehir ( cdt join ) , interview role last 90days laptop wifi available age 32.11 least graduat 12th pass diploma final year student given locat ssp comfort stipend & allow dure training current readi r3 process introduct self intro compani name purpos call book counsel session need gener ask like class perform etc .. question none abov non chargeabl delhi"

In [75]:
df = df.join(numerical_df, how='inner')

In [76]:
df.shape

(16386, 26)

In [77]:
df.head(30)

,id,Name,tags,pca0,pca1,pca2,pca3,pca4,pca5,pca6,...,pca13,pca14,pca15,pca16,pca17,pca18,pca19,pca20,pca21,pca22
0,0,[parida],"parida lipsa 25 femal orissa , famili bg - fat...",-0.052781,1.823040,-1.000861,-1.640338,2.153899,-0.904880,-3.322327,...,-1.002317,-0.186995,1.102233,0.585393,0.070028,-0.435301,0.148319,-0.219776,-0.664650,-0.621672
1,1,[shreej],shreej 29 yo femal unmarri msc financ uk 2022...,2.923109,-2.272580,1.616185,0.522408,1.446041,1.329056,-1.950287,...,-0.057405,-0.829778,0.279894,-0.026051,0.470935,0.000236,-0.025792,0.042607,-0.017964,-0.339394
2,2,[ms6744],ms6744 nm work current readi join r3 process i...,2.164853,-2.073269,-1.094714,-0.267596,-0.985760,0.299652,1.724536,...,-1.112322,0.481271,-0.121442,0.542240,0.176530,-0.313344,-0.809657,0.663573,0.696053,-0.599852
3,3,[aswalu],aswalu final interview done 22yr uttarakhand ...,3.906563,-3.405313,-0.106782,1.147585,0.310900,-0.251753,0.245191,...,-0.019635,0.724503,-0.090785,-0.022621,0.262717,-0.189576,-0.089993,-0.359328,0.102563,0.083939
4,4,[aniket],"aniket 22 male bhopal , ba grad 21 famili bg -...",-0.944235,-1.526629,1.590621,-1.558568,0.460823,-1.567873,1.634695,...,-1.064223,-0.125709,0.136476,0.183655,-0.484256,0.297118,-0.582925,-0.026695,-0.152585,0.173361
5,5,[faizal],faizal hd =25 ba - currenlti mba distanc say ...,-5.579654,1.342818,1.802116,-1.125968,-0.231680,-1.348032,0.860554,...,-0.929862,-0.408741,-0.051392,0.069074,0.323925,-1.018994,-0.631740,-0.394689,-0.914739,0.016413
6,6,[ravatn],ravatn bed 2021 bsc 2019 bglr - dono place it...,0.357986,-1.874188,0.130395,1.832301,-0.384434,-2.592920,-0.195161,...,1.088930,-0.580183,0.476081,-0.588453,-0.091987,-0.341109,-0.512780,0.039848,-0.247332,-0.548941
7,7,[gornal],gornal m.tech - 2022- fresher dad- farmer mom ...,-4.107792,-0.312133,-0.042394,0.061637,0.591363,-0.861360,-1.175065,...,0.377448,0.421239,-0.386704,0.761210,0.204665,-0.886725,0.201377,-0.709418,0.223291,0.346213
8,8,[Upkarr],"upkarr intro - eng comm guard gap , littl mti ...",-4.127144,-0.148558,0.721339,-0.615416,0.788534,0.103495,-0.389031,...,-0.334093,-0.089614,-0.952717,-0.831651,0.820648,0.396035,0.249185,0.217918,-0.493086,-0.559958
9,9,[moizju],moizju 25-bcom -2019- 1 yr exp sale -3.5lpa hy...,1.064749,1.544065,-1.415297,0.295471,0.678079,0.813304,1.556018,...,0.043823,-0.319144,-0.313713,0.065939,0.110292,0.432163,0.177648,-0.755487,0.143091,0.323624
10,10,[reetar],"reetar 26 , exp papers good commun skills conf...",3.662067,-2.768339,0.384850,-0.785214,-0.009577,0.050845,-0.179878,...,-0.031132,0.044589,0.020180,0.716380,0.212688,-0.048512,0.060563,-0.464129,0.560156,-0.271912
11,11,[dsubha],dsubha basic detail : 21 unmarri bsc math 202...,-3.372696,-0.670807,-0.573999,0.940253,0.818928,2.040037,-0.405185,...,0.605635,-0.771212,0.624543,-0.512222,0.073900,-1.441898,0.112654,-0.186699,-0.279861,0.066104
12,12,[kiran2],kiran2 age : 21 bcom fresher father- army moth...,-1.818909,-1.317670,1.283268,0.649655,1.234146,1.537863,-0.719028,...,0.435876,-0.063983,0.818516,0.285245,-0.970148,-1.060704,0.199482,0.078601,-0.039697,-0.459105
13,13,[sayang],"sayang bep bangalor is wb- kanuru bengali , h...",4.303772,3.664183,-2.481052,-0.755399,0.000569,-0.511417,0.424182,...,-0.269639,0.041660,-0.539910,0.415861,-1.244748,-0.039628,0.155611,-0.186957,-0.283769,-0.060853
14,14,[karnpr],karnpr left meet dure scenario rehir ( cdt jo...,-4.490662,-0.118188,1.725631,-1.759371,0.654387,0.677976,0.810323,...,1.546576,1.301552,-0.118568,-0.214882,-0.791568,0.185356,0.017485,-0.626027,0.218981,0.209629
15,15,[kvidya],"kvidya 25 yrs , male unmarried hindi bihar b. ...",-1.553381,2.912704,-0.977639,0.703115,1.148101,0.557470,-2.177114,...,0.102052,0.296458,0.016737,0.012058,-0.147508,0.252525,0.056441,-0.702867,0.443594,0.340145
16,16,[ashrim],ashrim age:26||qual : btech:2017||exp-in core ...,-2.030851,-1.037462,-2.093262,0.527376,-0.037749,0.018212,-0.301825,...,-0.657286,0.540256,-0.079868,-1.148137,-0.335316,-0.158846,-0.851413,-0.712224,-0.196655,0.252299
17,17,[abhina],abhina 20 yr old pratapgarh 2022ba fresher fa...,0.873836,-2.266683,0.457218,-0.258633,-1.714062,-1.225481,-0.278090,...,0.580470,-0.123944,0.098593,0.158298,-0.034393,0.406784,0.898636,0.166717,-0.110547,0.040259
18,18,[sanny1],sanny1 25yrs father farmer no-acquittq appli ...,-4.963258,0.023862,0.253976,1.237258,1.146516,1.549563,-0.696359,...,0.681346,0.527138,-0.256756,-1.016478,0.122066,-0.118400,-0.251975,-0.763535,-0.058425,-0.016449
19,19,[biswaj],biswaj west bengal age 24 unmarried b.e cse 20...,-2.439617,-0.825137,0.076065,-1.071948,1.250490,1.685029,-1.238515,...,-0.736385,0.069687,-0.684939,-0.892011,0.330855,-1.382522,0.759788,0.402867,-0.499759,0.150976
20,20,[akansh],akansh 26 yr -1.5 exp qualiti analyst-belong f...,4.836952,0.408831,0.352150,-0.793128,0.097486,-0.195135,-0.634512,...,-0.045763,-0.102605,0.005796,0.278013,0.307541,-0.103888,-0.002578,-0.469019,0.870814,-0.391134
21,21,[bharga],bharga 23|| bsc agriculture||seem veri nervou ...,-3.148938,-0.737570,0.747123,2.040185,-0.244947,-1.303550,1.149029,...,0.597611,-0.053795,0.197285,0.368438,-0.219465,0.090363,0.742263,-0.631289,0.357773,0.444263
22,22,[devvee],devve intro - fresher bsc bio 22 grad guard g...,-0.914529,-1.595385,1.365537,-0.230907,-0.949455,-0.830587,2.242753,...,0.709413,0.130840,-0.989705,0.203852,-0.868191,0.537953,-0.720562,-1.026072,0.352248,0.268232
23,23,[harshi],harshi nativ - agra21 bcom hon ( 2022 ) father...,1.120315,-2.367167,-0.480210,-1.568997,-0.586422,1.726304,0.928229,...,0.462121,-0.417924,-0.000270,0.648726,0.452539,-0.080770,-0.861547,-0.714111,0.285004,-0.413870
24,24,[saurab],"saurab candid ha done hi bsc ( 2017 ) , father...",3.348106,-2.178139,0.658260,1.257120,0.254508,-0.886652,-0.916160,...,-0.491415,-0.280841,-0.398691,0.386636,0.013869,-0.033513,-0.356351,-0.820295,0.134039,0.403303
25,25,[vijayg],"vijayg `` basic detail : hubly , age 25 bca 20...",1.212118,-0.887665,-3.089334,-0.152628,1.378567,-0.164922,-0.509817,...,0.246417,-0.772455,0.412167,-0.163316,0.421828,-0.430386,-1.153749,-0.717206,0.300327,0.528940
26,26,[sharma],sharma hd = 31.2 mba 2012 ha total work exp 1...,0.674077,6.501238,-0.947750,-1.259788,-0.286079,0.546671,0.474836,...,1.150378,-0.133149,0.552585,0.732355,0.570011,-0.707585,0.395929,-0.149963,-1.038214,0.300084
28,28,[wanifa],wanifa mba- marketig & hr - 2022- fresherdad- ...,-5.185894,0.209928,1.054371,1.658174,0.408787,-0.672895,-1.514442,...,-1.072936,-0.311121,-0.387530,0.663420,0.108116,0.639092,0.812111,0.258849,0.092131,-0.439724
29,29,[shukla],shukla 26 yo femal unmarri home scienc 2020 f...,-4.437526,-0.219451,2.000604,1.732820,-0.573099,0.933323,-0.171953,...,-0.371674,1.150742,1.319240,-0.037057,-0.058486,0.504416,-0.414906,-0.644049,0.216987,0.097175
30,30,[saivis],"saivi 23 yrs , male fresher unmarried telugu a...",-4.838966,-0.036580,1.584234,1.516105,0.400488,1.393866,0.416231,...,-0.613658,-0.187986,-0.374875,0.506668,-0.674232,0.445826,-0.518912,-0.104980,0.003033,0.319300

In [78]:
df['pca0'].unique()

array([-0.05278134,  2.92310863,  2.16485291, ...,  6.97187506,
        4.13991125,  1.47508752], shape=(16144,))

In [79]:
df.isnull().sum()

id       0
Name     0
tags     0
pca0     0
pca1     0
pca2     0
pca3     0
pca4     0
pca5     0
pca6     0
pca7     0
pca8     0
pca9     0
pca10    0
pca11    0
pca12    0
pca13    0
pca14    0
pca15    0
pca16    0
pca17    0
pca18    0
pca19    0
pca20    0
pca21    0
pca22    0
dtype: int64

<!-- ## Word Embeddings
**Note: Use Contextual Embeddings for More Accuracy**

To represent words in a numerical format while preserving their meaning and relationships, we will apply **word embeddings**. This helps in capturing semantic similarities and improving machine learning model performance.
(e.g., "king" â†’ similar to "queen" but different from "apple").

['stemming', 'reduces', 'words', 'to', 'root']  
[34402, 10838, 2616, 2000, 7771] -->

## Hugging Face Transformers

In [87]:
neural_df = df.copy()
neural_df.drop('Name', axis=1, inplace=True)
neural_df.head(1)

,id,tags,pca0,pca1,pca2,pca3,pca4,pca5,pca6,pca7,...,pca13,pca14,pca15,pca16,pca17,pca18,pca19,pca20,pca21,pca22
0,0,"parida lipsa 25 femal orissa , famili bg - fat...",-0.052781,1.82304,-1.000861,-1.640338,2.153899,-0.90488,-3.322327,2.383088,...,-1.002317,-0.186995,1.102233,0.585393,0.070028,-0.435301,0.148319,-0.219776,-0.66465,-0.621672

In [84]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

In [88]:
def get_text_embedding(text):
    inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True)

    with torch.no_grad():
        outputs = model(**inputs)

    embeddings = outputs.last_hidden_state.mean(dim=1)
    
    return embeddings.squeeze().numpy()

In [ ]:
neural_df['tags'] = neural_df['tags'].apply(get_text_embedding)